### ISSUE TITLE
UGRC website rebuild

### ISSUE THREAD

**Issue by brigsz** [agrc/planning-queue#313] opened 2023-12-19 00:12 UTC
### Benefit

Build UGRC's gis.utah.gov website to adhere to DGO guidelines for agency websites, using the Utah Design System, and other elements outlined by DGO and DTS.

### Acceptance Criteria

- Build website using [Astro](https://astro.build/). Create page templates for the types of pages required by gis.utah.gov
  - [x] Landing page
  - [x] Pillar page
  - [ ] Level 1 page
  - [ ] Level 2 page
  - [ ] Data page
  - [ ] Blog page
  - [ ] Documentation Page
 
### Notes

I am not sure what priority this is for DTS

### Risks

- Communicating with DTS what is needed by UGRC regarding the design system
- Obtain design system elements in a generic form to use in Astro
  - UGRC may not be able to adhere to all guidelines if DTS does not finish this task.
- Determine most important website pages/sections to have completed
- Create (or pull from existing site) content for pillar, level 1 and 2 pages deemed most important
 for most important pillar, level 1 and level 2 pages
- March deadline
- UGRC staff time to define website content

### Issue Reference

refs #

**Comment by steveoh** [comment] 2024-01-16 17:11
### Sprint 1 Notes

## January 9, 2024

1. I got access to the curated hero images and chose the hexagon one because... gis.
2. I got access to [[freepix](https://storyset.com/office)](https://storyset.com/office) and started using the cuate illustrations.
   1. Have licensing question out to Jospeh but maybe he’s not the right person. 
3. I started working on the contact page and the products/sgid page.
4. the /blog page and the /blog/* pages now all use the same layout but the markdown content still needs styling
5. I started with dark mode as well but it's very much a work in progress.

## January 10, 2024

1. Sorted out the logo naming
2. Added the required footer and made it responsive
3. Got the govOps logo 
    1. need an svg
4. Contacs page
    1. Need photos and titles of employees

## January 11, 2024

1. Started converting /sgid to a pillar page and created a reusable pillar layout
2. Converting contacts table to a list and got our team motivated to take some selfies

**Comment by steveoh** [comment] 2024-01-16 17:23
### Sprint 2

- [ ] Complete SGID pillar layout
- [ ] Create templates of other pillar pages so others can provide content
- [ ] Make sure I have components for level 1 and 2 pages
- [ ] Build as many layouts as possible

**Comment by nathankota** [comment] 2024-02-29 14:25
duplicate of #312

**Closed by nathankota** 2024-02-29 14:25 UTC
