### ISSUE TITLE
Migrate or Deprecate AGOL Minimalist Instant Apps

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#223] opened 2023-09-26 13:44 UTC
### Statement of Need

Esri AGOL Minimalist Instant app template is in [mature support](https://www.esri.com/arcgis-blog/products/instant-apps/announcements/instant-apps-announcement-minimalist-moving-to-mature-support-in-the-arcgis-online-october-2022-update/). Need to migrate all production apps in the UGRC AGOL that use that template to a different one.

## Benefit Hypothesis

Get ahead of the Minimalist app retirement.

## PI Acceptance Criteria

These are the apps that need to be migrated or deprecated. Check the ones that could be dealt with in FY24 Q1 PI.

- [x] [Utah Lidar Coverage](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=35d08d7d23ca4293b657d570f1005822), [Porter #236](https://github.com/agrc/porter/issues/236) - @rkelson 
- [x] [Qualifying Tracts](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=2a4985939d9f45dc89e9041e7715f452) - Jake (permission to deprecate provided Dec. 5, 2023)
- [x] [TURN and Nevada GPS Stations](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=95e0d153d1ce4ba39556c9f94284c68c), [Porter #237](https://github.com/agrc/porter/issues/237), @rkelson 

### Committed

now #383 
- ~[PLSS Monument Preservation Tie Sheet](http://utah.maps.arcgis.com/apps/Minimalist/index.html?appid=16b3f737cc024606a3fb0de815bd08fb), UtahAGRC, @DenisePeterson~

### Uncommitted

now #384 
- ~https://github.com/agrc/masquerade/issues/183, [Masquerade Demo](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=d9287c84bb754de78c834517205d7a62) - UtahAGRC, @stdavis~

### Possible deprecations

- [x] [UORG 2016 Unfunded Projects](http://utah.maps.arcgis.com/apps/Minimalist/index.html?appid=f2b60db703954e41a8020e271fdc412d) - UtahAGRC, @ZachBeck 
- [x] [Utah DABC Licenses](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=231799f7d43b42849552b0de85e63247) - @ZachBeck 
- [x] [DTS EIN Locations](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=d4aad4b19fea448da757385588ab620f) - @jacobdadams 

ref: #132

**Comment by stdavis** [comment] 2023-12-05 18:19
@nathankota Is this a duplicate of https://github.com/agrc/planning-queue/issues/132?

**Comment by nathankota** [comment] 2023-12-05 21:38
> @nathankota Is this a duplicate of #132?

Closed 132

**Comment by nathankota** [comment] 2023-12-05 21:39
Comments from Q1 Task (#132)
Steve:
> What do you think about adding DNS to these so the underlying url can migrate in the future without requiring a deprecation?

Rick:
> are you saying we could create lidarcoverage.utah.gov & turn.utah.gov for the apps?

Steve:
> pretty much

**Comment by nathankota** [comment] 2023-12-06 14:38
### Notes
#### December 5
- Justin Miller, DWS lead technical support, indicated that the [Qualifying Tracts](https://utah.maps.arcgis.com/apps/instant/minimalist/index.html?appid=2a4985939d9f45dc89e9041e7715f452) map and data is no longer used. Time to deprecate @jacobdadams

**Comment by nathankota** [comment] 2024-04-30 16:19
### Sprint 3
- Check nukeage date for EIN app...did we set a date? Can it be deleted this sprint?

**Comment by jacobdadams** [comment] 2024-06-20 14:39
DTS EIN app and data nuked. If someone wants something similar, it shouldn't be too hard to replicate.

**Closed** 2024-06-20 14:39 UTC
